### ISSUE TITLE
an error is reported after sending a message

### ISSUE THREAD

**Issue by Silentdoer** [skydoves/chatgpt-android#135]
something went wrong, please re-launch or re-install this app

**Comment by asolopovas** [comment]
Same here with version 1.0.8

**Comment by Aipra** [comment]
same problem

**Comment by bestofbest1** [comment]
(DefaultDispatcher-worker-54:240) clear cache & histories for Unauthorized and Forbidden
06:44:16.591 19934-20976 ChatGPTMessageWorker      com.skydoves.chatgpt        D  (DefaultDispatcher-worker-40:226) worker failure!
06:44:16.601 19934-19958 WM-WorkerWrapper          com.skydoves.chatgpt        E  Work [ id=a82e343d-5303-45dc-b44e-3c224d40467c, tags={ com.skydoves.chatgpt.feature.chat.worker.ChatGPTMessageWorker } ] failed because it threw an exception/error
                                                                                  java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Data cannot occupy more than 10240 bytes when serialized
                                                                                  	at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:516)
                                                                                  	at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:475)
                                                                                  	at androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:311)
                                                                                  	at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
                                                                                  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                  	at java.lang.Thread.run(Thread.java:1012)
                                                                                  Caused by: java.lang.IllegalStateException: Data cannot occupy more than 10240 bytes when serialized
                                                                                  	at androidx.work.Data.toByteArrayInternal(Data.java:407)
                                                                                  	at androidx.work.Data$Builder.build(Data.java:957)
                                                                                  	at com.skydoves.chatgpt.feature.chat.worker.ChatGPTMessageWorker.doWork(ChatGPTMessageWorker.kt:74)

**Comment by Aipra** [comment]
![IMG_20230511_155158.jpg](https://github.com/skydoves/chatgpt-android/assets/69207464/8159a3b6-33d5-4f4c-a805-cb1bf200c936)

Maybe invalid api key

**Comment by hamza94max** [comment]
Same with me

**Comment by boust3r** [comment]
Same here

**Comment by skydoves** [comment]
Hello everyone, I'm excited to announce that this repository has now migrated to utilize OpenAI's official chat API. Please refer to the [new guidelines](https://github.com/skydoves/chatgpt-android?tab=readme-ov-file#-how-to-build-the-project) for instructions on running this project. Thank you for your attention!
