### ISSUE TITLE
please help when i install tha app it crashes everytime and said to initialize firbase sdk first

### ISSUE THREAD

**Issue by tauheed0007** [skydoves/chatgpt-android#42]

**Comment by ubikapps** [comment]
On Android 13 on a Pixel 6 I get this too. Stack trace:
`2023-01-08 15:37:25.389 32713-32713 AndroidRuntime          com.skydoves.chatgpt                 E  FATAL EXCEPTION: main
                                                                                                    Process: com.skydoves.chatgpt, PID: 32713
                                                                                                    java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: androidx.startup.StartupException: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.skydoves.chatgpt. Make sure to call FirebaseApp.initializeApp(Context) first.
                                                                                                    	at android.app.ActivityThread.installProvider(ActivityThread.java:7467)
                                                                                                    	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6973)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6744)
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2133)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7872)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
                                                                                                    Caused by: androidx.startup.StartupException: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.skydoves.chatgpt. Make sure to call FirebaseApp.initializeApp(Context) first.
                                                                                                    	at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:187)
                                                                                                    	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:238)
                                                                                                    	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:206)
                                                                                                    	at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:45)
                                                                                                    	at android.content.ContentProvider.attachInfo(ContentProvider.java:2451)
                                                                                                    	at android.content.ContentProvider.attachInfo(ContentProvider.java:2421)
                                                                                                    	at android.app.ActivityThread.installProvider(ActivityThread.java:7462)
                                                                                                    	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6973) 
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6744) 
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2133) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201) 
                                                                                                    	at android.os.Looper.loop(Looper.java:288) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7872) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936) 
                                                                                                    Caused by: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.skydoves.chatgpt. Make sure to call FirebaseApp.initializeApp(Context) first.
                                                                                                    	at com.google.firebase.FirebaseApp.getInstance(FirebaseApp.java:186)
                                                                                                    	at com.google.firebase.messaging.FirebaseMessaging.getInstance(FirebaseMessaging.java:137)
                                                                                                    	at io.getstream.chat.android.pushprovider.firebase.FirebasePushDeviceGenerator.<init>(FirebasePushDeviceGenerator.kt:32)
                                                                                                    	at com.skydoves.chatgpt.feature.chat.initializer.StreamChatInitializer.createNotificationConfig(StreamChatInitializer.kt:89)
                                                                                                    	at com.skydoves.chatgpt.feature.chat.initializer.StreamChatInitializer.create(StreamChatInitializer.kt:68)
                                                                                                    	at com.skydoves.chatgpt.feature.chat.initializer.StreamChatInitializer.create(StreamChatInitializer.kt:42)
                                                                                                    	at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:180)
                                                                                                    	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:238) 
                                                                                                    	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:206) 
                                                                                                    	at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:45) 
                                                                                                    	at android.content.ContentProvider.attachInfo(ContentProvider.java:2451) 
                                                                                                    	at android.content.ContentProvider.attachInfo(ContentProvider.java:2421) 
                                                                                                    	at android.app.ActivityThread.installProvider(ActivityThread.java:7462) 
                                                                                                    	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6973) 
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6744) 
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2133) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201) 
                                                                                                    	at android.os.Looper.loop(Looper.java:288) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7872) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936) 
`

**Comment by ubikapps** [comment]
google-services.json seems to be missing so Firebase is not going to work when building from github source. I commented out line 68 of StreamChatInitializer.kt and it launches the app

**Comment by skydoves** [comment]
Please pull the new commits of this project and rebuild. Firebase relevant features were removed recently. Thank you!
