### ISSUE TITLE
Error: FirebaseApp is not initialized in this process com.skydoves.chatgpt.

### ISSUE THREAD

**Issue by dev-aniketj** [skydoves/chatgpt-android#52]
## It shows the Runtime Exception when I run it on my device.

**Error :** 
```xml
java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: androidx.startup.StartupException: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.skydoves.chatgpt. Make sure to call FirebaseApp.initializeApp(Context) first.
	at android.app.ActivityThread.installProvider(ActivityThread.java:7849)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7355)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7083)
	at android.app.ActivityThread.access$1700(ActivityThread.java:277)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2170)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8285)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1074)
Caused by: androidx.startup.StartupException: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.skydoves.chatgpt. Make sure to call FirebaseApp.initializeApp(Context) first.
	at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:187)
	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:238)
	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:206)
	at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:45)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2421)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2386)
	at android.app.ActivityThread.installProvider(ActivityThread.java:7844)
	... 11 more
Caused by: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.skydoves.chatgpt. Make sure to call FirebaseApp.initializeApp(Context) first.
	at com.google.firebase.FirebaseApp.getInstance(FirebaseApp.java:186)
	at com.google.firebase.messaging.FirebaseMessaging.getInstance(FirebaseMessaging.java:137)
	at io.getstream.chat.android.pushprovider.firebase.FirebasePushDeviceGenerator.<init>(FirebasePushDeviceGenerator.kt:32)
	at com.skydoves.chatgpt.feature.chat.initializer.StreamChatInitializer.createNotificationConfig(StreamChatInitializer.kt:89)
	at com.skydoves.chatgpt.feature.chat.initializer.StreamChatInitializer.create(StreamChatInitializer.kt:68)
	at com.skydoves.chatgpt.feature.chat.initializer.StreamChatInitializer.create(StreamChatInitializer.kt:42)
	at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:180)
	... 17 more
```

**Comment by AmitAdsum9796** [comment]
Same issue we can faced.

**Comment by navneetboghani** [comment]
Same issue i have occur.

**Comment by skydoves** [comment]
Hey guys, please pull the recent commits and build again. I just removed the push notification feature. Thanks!

**Comment by dev-aniketj** [comment]
This error is solved but facing another [ISSUE](https://github.com/skydoves/chatgpt-android/issues/57)
