### ISSUE TITLE
RuntimeException: apiKey is not defined in Builder

### ISSUE THREAD

**Issue by dev-aniketj** [skydoves/chatgpt-android#57]
### Error :
```
java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: androidx.startup.StartupException: java.lang.IllegalStateException: apiKey is not defined in Builder
	at android.app.ActivityThread.installProvider(ActivityThread.java:7849)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7355)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7083)
	at android.app.ActivityThread.access$1700(ActivityThread.java:277)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2170)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8285)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1074)
Caused by: androidx.startup.StartupException: java.lang.IllegalStateException: apiKey is not defined in Builder
	at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:187)
	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:238)
	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:206)
	at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:45)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2421)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2386)
	at android.app.ActivityThread.installProvider(ActivityThread.java:7844)
	... 11 more
Caused by: java.lang.IllegalStateException: apiKey is not defined in Builder
	at io.getstream.chat.android.client.ChatClient$Builder.internalBuild(ChatClient.kt:2937)
	at io.getstream.chat.android.client.ChatClient$ChatClientBuilder.build(ChatClient.kt:3038)
	at io.getstream.chat.android.client.ChatClient$Builder.build(ChatClient.kt:2925)
	at com.skydoves.chatgpt.feature.chat.initializer.StreamChatInitializer.create(StreamChatInitializer.kt:65)
	at com.skydoves.chatgpt.feature.chat.initializer.StreamChatInitializer.create(StreamChatInitializer.kt:37)
	at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:180)
	... 17 more
```

**Comment by skydoves** [comment]
Please build this project following [the guidance](https://github.com/skydoves/chatgpt-android#-how-to-build-the-project).
